# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d11de8617613d500a269568efd10a1630d78ba414fcb293fc21521e6c90ab42e8d15624c145e6c7a3fbdfac979f6dd21819be8d23f4920fcaa4d457141d1e3f

test:
  secret_key_base: b379b0b76be7077d3f774242d3a97d90ab03cb0fa1275477d9a21a15abfaa9cc0da109fc8747276d24eac36f0afbfeb6a00d8b74df39cc19dab6831b2bde0d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
